name: 'The name of your action here TODO'
description: 'Provide a description here TODO'
author: 'Your name or organization here TODO'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  WORKSPACE_ID:
    description: "Your zenhub workspace's ID"
    required: true

# Define your outputs here.
outputs:
  markdownContent:
    description: 'Mardown content'
  markdownFile:
    description: 'Generated markdown file'

#runs:
#  using: 'composite'
#  steps:
#    # Reference the major version of a release
#    - uses: actions/checkout@v4
#    - run: |
#        ls -alh
#        echo "----"
#        pwd
#        echo "----"
#        ls -alh zenhub_report_action
#        npm ci && npx -y ts-node src/index.ts
#      shell: bash
#      env:
#        GH_API_KEY: ${{ github.token }}
#        REPO_ID: ${{ github.event.repository.id }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - run: |
        npm ci
      shell: bash
      name: NPM build

    - run: |
        node dist/index.ts
      shell: bash
      env:
        GH_API_KEY: ${{ github.token }}
        REPO_ID: ${{ github.event.repository.id }}
      name: Node run

#runs:
#  using: node20
#  main: dist/index.js
