name: 'The name of your action here TODO'
description: 'Provide a description here TODO'
author: 'Your name or organization here TODO'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  WORKSPACE_ID:
    description: "Your zenhub workspace's ID"
    required: true
  REPO_ID:
    description: 'Your github repo ID'
    required: true
  FROM_PIPELINE:
    description: 'Zenhub start pipeline'
    required: true
  TO_PIPELINE:
    description: 'Zenhub completed pipeline'
    required: true
  FROM_DATE:
    description: 'Start date'
    required: false
  TO_DATE:
    description: 'End date'
    required: false

# Define your outputs here.
outputs:
  markdownContent:
    description: 'Mardown content'
  markdownFile:
    description: 'Generated markdown file'

runs:
  using: node20
  main: dist/index.js
