name: 'The name of your action here TODO'
description: 'Provide a description here TODO'
author: 'Your name or organization here TODO'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
#inputs:
#  milliseconds:
#    description: 'Your input description here'
#    required: true
#    default: '1000'

# Define your outputs here.
outputs:
  markdownContent:
    description: 'Mardown content'
  markdownFile:
    description: 'Generated markdown file'

#runs:
#  using: node20
#  main: src/zenhub_reports/dist/bundle.js

runs:
  using: "composite"
  steps:
    # Reference the major version of a release
    - uses: actions/checkout@v4
    - run: npx -y ts-node src/index.ts
      shell: bash